### ISSUE TITLE
"Recommendations for Implementation" document

### ISSUE THREAD

**Issue by laura-alagna** [dpscollaborative/btr-planning#15]
This document is drafted here: https://docs.google.com/document/d/1cb--DlQr_fDTYzcn3fsXa_ynC1O9rhCiMrXCkMq-lD8/edit

There are several pieces that need to be worked on:
- [ ] Section for depositors (#10)
- [ ] Section for DDPs (#11)
- [ ] The document should be edited (#12)
- [ ] The document should be reviewed by the entire team (#13)
- [ ] The team should discuss on a call to make sure we are all in agreement (#14)
